### ISSUE TITLE
 Add Sex

### ISSUE THREAD

**Issue by Krixx1337** [qxdFox/Aiodob-Client-DDNet#3]
Teeworlds is cool and all, but where's the sex? Add a mode where Tees can fall in love or something. Maybe throw in heart grenades and sexy skins too. Make it happen, thanks.

**Comment by fluffysnaff** [comment]
Yes daddy please add this

**Comment by qxdFox** [comment]
aint no way theres two people wanting this.
Maybe ill actually consider making ONE version for this 
but I aint a coder, I steal code, don't expect much if i actually decide to

**Comment by fluffysnaff** [comment]
how is the list coming along?

**Comment by k-i-o** [comment]
add sex +rep

**Comment by kbbytes** [comment]
add sex yaaaaaaay +rep

**Comment by fluffysnaff** [comment]
bump

**Comment by fluffysnaff** [comment]
bump

**Comment by fluffysnaff** [comment]
please, bump

**Comment by qxdFox** [comment]
> please, bump

very desperate for it

**Comment by fluffysnaff** [comment]
bump

**Comment by fluffysnaff** [comment]
soon 1 month and no progress :(

**Comment by qxdFox** [comment]
idk man doesnt seem that important..

**Comment by k-i-o** [comment]
add sex

**Comment by fluffysnaff** [comment]
Doesn't seem important? Only like 4 people want it

**Comment by k-i-o** [comment]
add sex

**Comment by qxdFox** [comment]
no can do
